# Generated by Django 2.2.7 on 2019-11-05 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='telefone',
        ),
        migrations.CreateModel(
            name='Dono_estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('telefone', models.CharField(max_length=19, verbose_name='Celular')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='dono_estabelecimemto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Dono_estabelecimento'),
            preserve_default=False,
        ),
    ]
