# Generated by Django 2.2.7 on 2019-11-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191104_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estabelecimento'),
        ),
    ]
